/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
package pl.lemanski.pandaloop.core.engine.jni

object PandaLoopJNI {
    @JvmStatic
    external fun initialize_recording(jarg1: Long, jarg2: Int, jarg3: Int): Int
    @JvmStatic
    external fun uninitialize_recording()
    @JvmStatic
    external fun stop_recording(jarg1: Long): ByteArray?
    @JvmStatic
    external fun start_recording(): Int
    @JvmStatic
    external fun initialize_playback_device(jarg1: Int, jarg2: Int): Int
    @JvmStatic
    external fun set_playback_buffer(jarg1: ByteArray?, jarg2: Long): Int
    @JvmStatic
    external fun uninitialize_playback_device()
    @JvmStatic
    external fun start_playback(): Int
    @JvmStatic
    external fun stop_playback()
    @JvmStatic
    external fun get_playback_devices_count(): Int
    @JvmStatic
    external fun get_bytes_per_frame(jarg1: Int): Int
    @JvmStatic
    external fun save_audio_file(jarg1: String?, jarg2: ByteArray?, jarg3: Int, jarg4: Int, jarg5: Int): Int
    @JvmStatic
    external fun load_audio_file(jarg1: Long, jarg2: String?): ByteArray?
}
